import { em } from 'enumwaii';

import { CHARACTER_ASSISTANT_TOOL_NAME_ENUM, CHARACTER_ASSISTANT_TOOL_NAMES } from './character-assistant-contracts';

export const ASSISTANT_TOOL_RENDERER_KINDS_ENUM = em(['CONCEPT', 'DISCOVERY', 'PROPOSAL']);
export const ASSISTANT_TOOL_RENDERER_KINDS = ASSISTANT_TOOL_RENDERER_KINDS_ENUM.enum;

const RENDERED_TOOL_ENUM = CHARACTER_ASSISTANT_TOOL_NAME_ENUM.omit([CHARACTER_ASSISTANT_TOOL_NAMES.READ_CHARACTER]);
const TOOL_RENDERER_REGISTRY = RENDERED_TOOL_ENUM.deriveTo(
  ASSISTANT_TOOL_RENDERER_KINDS_ENUM,
  [CHARACTER_ASSISTANT_TOOL_NAMES.RECORD_CONCEPT, ASSISTANT_TOOL_RENDERER_KINDS.CONCEPT],
  [CHARACTER_ASSISTANT_TOOL_NAMES.PROPOSE_CHARACTER_FIELDS, ASSISTANT_TOOL_RENDERER_KINDS.PROPOSAL],
  [CHARACTER_ASSISTANT_TOOL_NAMES.PROPOSE_TAGS, ASSISTANT_TOOL_RENDERER_KINDS.PROPOSAL],
  [CHARACTER_ASSISTANT_TOOL_NAMES.PROPOSE_ALTERNATE_GREETINGS, ASSISTANT_TOOL_RENDERER_KINDS.PROPOSAL],
  [CHARACTER_ASSISTANT_TOOL_NAMES.PROPOSE_CUSTOM_FIELDS, ASSISTANT_TOOL_RENDERER_KINDS.PROPOSAL],
  [CHARACTER_ASSISTANT_TOOL_NAMES.PROPOSE_CHARACTER_BOOK, ASSISTANT_TOOL_RENDERER_KINDS.PROPOSAL],
  [CHARACTER_ASSISTANT_TOOL_NAMES.SUGGEST_CHARACTER_DIRECTIONS, ASSISTANT_TOOL_RENDERER_KINDS.DISCOVERY],
);

export function getAssistantToolRendererKind(toolName: string) {
  const parsedTool = RENDERED_TOOL_ENUM.safeParse(toolName);
  return parsedTool.success ? TOOL_RENDERER_REGISTRY.get(parsedTool.value) : null;
}
