/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ApiCharacterVisionRouteImport } from './routes/api/character-vision';
import { Route as ApiCharacterGenerateRouteImport } from './routes/api/character-generate';
import { Route as ApiCharacterAssistantRouteImport } from './routes/api/character-assistant';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiCharacterVisionRoute = ApiCharacterVisionRouteImport.update({
  id: '/api/character-vision',
  path: '/api/character-vision',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiCharacterGenerateRoute = ApiCharacterGenerateRouteImport.update({
  id: '/api/character-generate',
  path: '/api/character-generate',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiCharacterAssistantRoute = ApiCharacterAssistantRouteImport.update({
  id: '/api/character-assistant',
  path: '/api/character-assistant',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/api/character-assistant': typeof ApiCharacterAssistantRoute;
  '/api/character-generate': typeof ApiCharacterGenerateRoute;
  '/api/character-vision': typeof ApiCharacterVisionRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/api/character-assistant': typeof ApiCharacterAssistantRoute;
  '/api/character-generate': typeof ApiCharacterGenerateRoute;
  '/api/character-vision': typeof ApiCharacterVisionRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/api/character-assistant': typeof ApiCharacterAssistantRoute;
  '/api/character-generate': typeof ApiCharacterGenerateRoute;
  '/api/character-vision': typeof ApiCharacterVisionRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/api/character-assistant'
    | '/api/character-generate'
    | '/api/character-vision';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/api/character-assistant'
    | '/api/character-generate'
    | '/api/character-vision';
  id:
    | '__root__'
    | '/'
    | '/api/character-assistant'
    | '/api/character-generate'
    | '/api/character-vision';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiCharacterAssistantRoute: typeof ApiCharacterAssistantRoute;
  ApiCharacterGenerateRoute: typeof ApiCharacterGenerateRoute;
  ApiCharacterVisionRoute: typeof ApiCharacterVisionRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/character-vision': {
      id: '/api/character-vision';
      path: '/api/character-vision';
      fullPath: '/api/character-vision';
      preLoaderRoute: typeof ApiCharacterVisionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/character-generate': {
      id: '/api/character-generate';
      path: '/api/character-generate';
      fullPath: '/api/character-generate';
      preLoaderRoute: typeof ApiCharacterGenerateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/character-assistant': {
      id: '/api/character-assistant';
      path: '/api/character-assistant';
      fullPath: '/api/character-assistant';
      preLoaderRoute: typeof ApiCharacterAssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCharacterAssistantRoute: ApiCharacterAssistantRoute,
  ApiCharacterGenerateRoute: ApiCharacterGenerateRoute,
  ApiCharacterVisionRoute: ApiCharacterVisionRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
